services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: "alawys"
    environment:
      POSTGRES_USER: nextjs_user
      POSTGRES_PASSWORD: nextjs_password
      POSTGRES_DB: nextjs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
